Repository lan-solo-capstone/freeshare, pull requests merged in 2021-04, with the labels that each got.

#177 modalFix
  client/components/MapAllItems.js
  client/components/Navbar.js
  client/components/SingleItemView.js
Labels: bug, style

#175 Jae25 secure api routes and bug fixes
  client/components/AllUsers.js
  client/components/SingleItemView.js
  client/components/User.js
  client/components/chat/InboxComponent.js
  client/store/chat.js
  client/store/useritems.js
  server/api/channels.js
  server/api/index.js
  server/api/items.js
  server/api/messages.js
  server/api/middleware.js
  server/api/users.js
  server/api/users.spec.js
Labels: bug

#180 fix: filter closed items from rendering
  client/components/Items.js
Labels: style

#181 Toast notification refactor
  client/components/EditItemForm.js
  client/components/NewItemForm.js
  client/components/SingleItemView.js
  client/store/item.js
  server/api/items.js
Labels: enhancement

#193 Allow admin delete items
  client/components/SingleItemView.js
  client/store/items.js
  server/api/items.js
  server/api/users.js
Labels: enhancement

#202 Sort items by date
  client/components/Items.js
Labels: style

#197 Toast upon edit user
  client/components/UserHome.js
  client/routes.js
  client/store/singleUser.js
Labels: style

#205 Disable submit button closes #201
  client/components/AllUsers.js
  client/components/EditItemForm.js
  client/components/EditUserForm.js
  client/components/ItemForm.js
  client/components/NewItemForm.js
  client/components/User.js
  client/components/UserHome.js
  client/components/UserView.js
Labels: enhancement, style

#225 refactor: toast messages shortened
  client/components/SingleItemView.js
  client/components/UserHome.js
  client/store/item.js
  client/store/singleUser.js
Labels: style

#232 Fix prop types error radio buttons
  client/components/EditItemForm.js
  client/components/ItemForm.js
Labels: bug

#231 Admin view sort items by date
  client/components/AllUsers.js
  client/store/useritems.js
Labels: style

#239 Form validate sign up zip and state
  client/components/AuthForm.js
Labels: style
