Repository lan-solo-capstone/freeshare, pull requests merged in 2021-03, with the labels that each got.

#4 chore: update prettier in devdependencies
  package.json
Labels: enhancement

#19 Yoshie branch1
  script/seed.js
  server/api/users.js
  server/db/models/index.js
  server/db/models/item.js
  server/db/models/itemPhoto.js
  server/db/models/user.js
  server/index.js
Labels: week1

#20 MapAllItems and MapSingleItem components written
  client/components/MapAllItems.js
  client/components/MapExp.js
  client/components/MapSingleItem.js
  client/components/index.js
  client/components/temp.js
  client/routes.js
Labels: week1

#23 Form new item
  .eslintrc.json
  client/components/NewItemForm.js
  client/components/index.js
  client/components/navbar.js
  client/routes.js
  client/store/item-jae.js
  package-lock.json
  server/api/index.js
  server/api/newitemform.js
  server/api/users.js
  server/db/models/item.js
Labels: week1

#24 chore: add export for NewItemForm
  client/components/index.js
Labels: week1

#26 Form new item part02
  .eslintrc.json
  client/components/NewItemForm.js
  script/seed.js
Labels: week1

#27 Feat: Mobile View touchup
  client/components/listAll.js
  client/components/singleItem.js
  package-lock.json
  package.json
  public/style.css
  server/index.js
Labels: week1

#31 Form new item part03
  client/components/NewItemForm.js
  client/store/item-jae.js
  package-lock.json
Labels: week1

#34 Single view component
  client/components/index.js
  client/components/listAll.js
  client/components/singleItem.js
  client/components/singleView.js
  client/routes.js
  public/style.css
  server/api/listAll.js
Labels: week1

#36 Admin view of all users
  client/components/AllUsers.js
  client/components/NewItemForm.js
  client/components/index.js
  client/routes.js
  client/store/index.js
  client/store/item-jae.js
  client/store/users.js
  package-lock.json
  package.json
  server/api/newitemform.js
  server/api/users.js
  server/index.js
Labels: week1

#40 Signupintegration connected signup form to backend with mapBox API call to resolve geoCoords
  client/components/auth-form.js
  client/components/temp.js
  client/components/user-home.js
  client/store/user.js
  package-lock.json
  package.json
  server/auth/index.js
Labels: week1

#41 Yoshie03
  client/components/NewItemForm.js
  client/store/item-jae.js
  script/seed.js
  server/api/index.js
  server/api/newitemform.js
  server/api/view_images.js
  server/db/models/user.js
Labels: week1

#42 Admin panel
  client/components/AllUsers.js
  client/components/EditUserForm.js
  client/components/User.js
  client/components/UserView.js
  client/components/index.js
  client/routes.js
  client/store/index.js
  client/store/singleUser.js
  client/store/user.js
  client/store/users.js
  package-lock.json
  package.json
  server/api/users.js
Labels: week1

#51 Navbar viewmap share
  client/components/listAll.js
  client/components/mobileFooter.js
  client/components/navbar.js
  client/components/singleView.js
  client/components/user-home.js
  public/style.css
Labels: week1

#53 tried react-map-gl popup, not going well
  client/components/MapAllItems.js
  package-lock.json
  server/auth/index.js
Labels: enhancement, week2

#54 Refactor 01
  client/components/AuthForm.js
  client/components/Items.js
  client/components/NewItemForm.js
  client/components/SingleItemView.js
  client/components/UserHome.js
  client/components/index.js
  client/components/mobileFooter.js
  client/components/navbar.js
  client/components/singleItem.js
  client/components/user-home.spec.js
  client/routes.js
  client/store/index.js
  client/store/item.js
  client/store/items.js
  package-lock.json
  server/api/index.js
  server/api/items.js
  server/api/listAll.js
  server/api/newitemform.js
  server/api/users.js
Labels: enhancement, week2

#55 refactor 02
  client/components/MobileFooter.js
  client/components/Navbar.js
  client/components/SingleItem.js
  server/api/newitemform.js
Labels: enhancement

#57 fix: EditUserForm pre-populates with the correct user's info
  client/components/EditUserForm.js
Labels: enhancement, week2

#60 User info items
  .babelrc
  .gitignore
  client/components/Items.js
  client/components/MobileFooter.js
  client/components/Navbar.js
  client/components/NewItemForm.js
  client/components/SingleItem.js
  client/components/SingleItemView.js
  client/components/UserHome.js
  client/routes.js
  client/store/index.js
  client/store/navbar.js
  client/store/user.js
  client/store/useritems.js
  package-lock.json
  package.json
  script/seed.js
  server/api/items.js
  server/api/users.js
  server/auth/google.js
Labels: week2

#64 cleaning up after mini-merge from hell
  .babelrc
  client/components/UserHome.js
  package-lock.json
  package.json
  server/api/items.js
  server/index.js
  webpack.config.js
Labels: week2

#70 travis: activate deployment
  .travis.yml
Labels: enhancement

#71 chore: add app name and provider
  .travis.yml
Labels: deployment, week2

#74 Jae10 fixes #73
  .travis.yml
  public/bundle.js
  public/bundle.js.map
Labels: deployment

#75 trying to fix travis
  .travis.yml
Labels: deployment

#83 try travis again
  .travis.yml
Labels: deployment

#87 Search more
  client/components/MapAllItems.js
  client/components/MapSingleItem.js
  client/components/SearchBox.js
  client/components/UserHome.js
Labels: enhancement, week2

#106 feat: button to mark item as Closed
  client/app.js
  client/components/SingleItemView.js
  client/components/chat/ChatContainer.js
  client/components/chat/Message.js
  client/components/chat/MessageList.js
  client/components/chat/NewMessageEntry.js
  client/routes.js
  client/store/chat.js
  client/store/item.js
  package-lock.json
  package.json
  server/api/items.js
  server/api/messages.js
  server/index.js
  webpack.config.js
Labels: enhancement, week2

#117 chore: npm install
  package-lock.json
Labels: enhancement

#118 reverted the forced id values in seed data
  script/seedData/channelsSeedData.js
  script/seedData/itemPhotoSeedData.js
  script/seedData/itemSeedData.js
  script/seedData/messagesSeedData.js
Labels: bug

#122 Feat: messaging feature
  client/components/Navbar.js
  client/components/SingleItemView.js
  client/components/chat/ChatContainer.js
  client/components/chat/InboxComponent.js
  client/components/chat/InboxOnly.js
  client/components/chat/Message.js
  client/components/chat/MessageList.js
  client/components/chat/NewMessageEntry.js
  client/components/index.js
  client/routes.js
  package-lock.json
  package.json
  server/db/models/channel.js
Labels: enhancement

#135 Jae18 mark item as open
  client/components/EditItemForm.js
  client/components/ItemForm.js
  client/components/NewItemForm.js
  client/components/SingleItem.js
  client/components/SingleItemView.js
  client/components/index.js
  client/store/item.js
  server/api/items.js
  server/db/models/item.js
Labels: enhancement

#136 New branch
  client/components/AuthForm.js
  client/components/UserHome.js
  client/store/singleUser.js
  server/api/users.js
  server/auth/index.js
  server/db/models/user.js
Labels: enhancement

#144 pre-populate editing form for items
  .gitignore
  client/components/EditItemForm.js
  client/components/EditUserForm.js
  client/components/ItemForm.js
  server/api/users.js
Labels: enhancement

#150 fix: typo in alertReference
  client/components/ItemForm.js
Labels: bug

#151 add middleware to attempt force https on heroku
  server/index.js
Labels: deployment

#160 Jae24 minor bug fixes
  client/components/ItemForm.js
  client/components/NewItemForm.js
  client/components/UserHome.js
  client/components/chat/InboxComponent.js
  script/deploy
  server/index.js
Labels: enhancement

#170 Mja styles
  README.md
  client/components/AuthForm.js
  client/components/EditUserForm.js
  client/components/User.js
Labels: style
